<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.users.app.exception.GlobalExceptionHandlerTest" tests="5" skipped="0" failures="0" errors="0" timestamp="2025-05-23T03:34:20.404Z" hostname="BOG1-LMC-MXMH2TWDJ5" time="0.01">
  <properties/>
  <testcase name="testHandleUnauthorizedException_shouldReturnUnauthorized()" classname="com.users.app.exception.GlobalExceptionHandlerTest" time="0.008"/>
  <testcase name="testHandleException_shouldReturnInternalServerError()" classname="com.users.app.exception.GlobalExceptionHandlerTest" time="0.0"/>
  <testcase name="testHandleUserAlreadyExists_shouldReturnConflict()" classname="com.users.app.exception.GlobalExceptionHandlerTest" time="0.0"/>
  <testcase name="testHandleRuntimeException_shouldReturnBadRequest()" classname="com.users.app.exception.GlobalExceptionHandlerTest" time="0.0"/>
  <testcase name="testHandleNotFoundException_shouldReturnNotFound()" classname="com.users.app.exception.GlobalExceptionHandlerTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
